import "dart:async";
import "dart:ui";

import "package:material_ui/material_ui.dart";
import "package:refreshed/get_navigation/get_navigation.dart";
import "package:refreshed/utils.dart";

/// Callback signature for tap events on a `GetSnackBar`.
typedef OnTap = void Function(GetSnackBar snack);

/// Callback signature for hover events on a `GetSnackBar`.
typedef OnHover = void Function(
  GetSnackBar snack,
  SnackHoverState snackHoverState,
);

/// Callback signature for status changes on a `GetSnackBar`.
typedef SnackbarStatusCallback = void Function(SnackbarStatus? status);

/// A custom `StatefulWidget` for displaying snack bars.
///
/// This widget provides functionality for displaying snack bars with customizable behavior and appearance.
class GetSnackBar extends StatefulWidget {
  /// Constructs a new instance of [GetSnackBar].
  const GetSnackBar(
    this.titleText, {
    super.key,
    this.maxWidth,
    this.margin = EdgeInsets.zero,
    this.padding = const EdgeInsets.all(16),
    this.borderRadius = 0.0,
    this.boxShadows,
    this.disableSelfAlignment = false,
    this.onHover,
    this.duration = const Duration(milliseconds: 1500),
    this.isDismissible = true,
    this.dismissDirection,
    this.snackPosition = SnackPosition.bottom,
    this.snackStyle = SnackStyle.floating,
    this.forwardAnimationCurve = Curves.easeOutCirc,
    this.reverseAnimationCurve = Curves.easeOutCirc,
    this.animationDuration = const Duration(seconds: 1),
    this.barBlur = 0.0,
    this.overlayBlur = 0.0,
    this.overlayColor = Colors.transparent,
    this.snackbarStatus,
    this.hitTestBehavior,
  });

  /// A callback for you to listen to the different Snack status
  final SnackbarStatusCallback? snackbarStatus;

  /// Defines how the snack bar area, including margin, will behave during hit testing.
  ///
  /// If this property is null and [margin] is not null, then [HitTestBehavior.deferToChild] is used by default.
  ///
  /// Please refer to [HitTestBehavior] for a detailed explanation of every behavior.
  final HitTestBehavior? hitTestBehavior;

  /// The direction in which the SnackBar can be dismissed.
  ///
  /// Default is [DismissDirection.down] when
  /// [snackPosition] == [SnackPosition.bottom] and [DismissDirection.up]
  /// when [snackPosition] == [SnackPosition.top]
  final DismissDirection? dismissDirection;

  /// Replaces [title]. Although this accepts a [Widget], it is meant
  /// to receive [Text] or [RichText]
  final Widget titleText;

  /// A callback that registers the user's hover anywhere over the Snackbar.
  final OnHover? onHover;

  /// How long until Snack will hide itself (be dismissed).
  /// To make it indefinite, leave it null.
  final Duration? duration;

  /// Determines if the user can swipe or click the overlay
  /// (if [overlayBlur] > 0) to dismiss.
  /// It is recommended that you set [duration] != null if this is false.
  /// If the user swipes to dismiss or clicks the overlay, no value
  /// will be returned.
  final bool isDismissible;

  /// Disabling the Alignment widget, this modification ensures that when a snack bar appears,
  /// it overlays the entire screen according to its height,
  /// making widgets in that portion inaccessible. Setting disableSelfAlignment to true disables self-alignment,
  /// allowing access to background widgets while the snack bar is visible.
  final bool disableSelfAlignment;

  /// Used to limit Snack width (usually on large screens)
  final double? maxWidth;

  /// Adds a custom margin to Snack
  final EdgeInsets margin;

  /// Adds a custom padding to Snack
  /// The default follows material design guide line
  final EdgeInsets padding;

  /// Adds a radius to all corners of Snack. Best combined with [margin].
  /// I do not recommend using it with [showProgressIndicator]
  /// or [leftBarIndicatorColor].
  final double borderRadius;

  /// [boxShadows] The shadows generated by Snack. Leave it null if you don't want a shadow.
  /// You can use more than one if you feel the need.
  final List<BoxShadow>? boxShadows;

  /// Snack can be based on [SnackPosition.top] or on [SnackPosition.bottom]
  /// of your screen.
  /// [SnackPosition.bottom] is the default.
  final SnackPosition snackPosition;

  /// Snack can be floating or be grounded to the edge of the screen.
  /// If grounded, I do not recommend using [margin] or [borderRadius].
  /// [SnackStyle.floating] is the default
  /// If grounded, I do not recommend using a [backgroundColor] with
  /// transparency or [barBlur]
  final SnackStyle snackStyle;

  /// The [Curve] animation used when show() is called.
  /// [Curves.easeOut] is default
  final Curve forwardAnimationCurve;

  /// The [Curve] animation used when dismiss() is called.
  /// [Curves.fastOutSlowIn] is default
  final Curve reverseAnimationCurve;

  /// Use it to speed up or slow down the animation duration
  final Duration animationDuration;

  /// Default is 0.0. If different than 0.0, blurs only Snack's background.
  /// To take effect, make sure your [backgroundColor] has some opacity.
  /// The greater the value, the greater the blur.
  final double barBlur;

  /// Default is 0.0. If different than 0.0, creates a blurred
  /// overlay that prevents the user from interacting with the screen.
  /// The greater the value, the greater the blur.
  final double overlayBlur;

  /// Default is [Colors.transparent]. Only takes effect if [overlayBlur] > 0.0.
  /// Make sure you use a color with transparency here e.g.
  /// Colors.grey[600].withOpacity(0.2).
  final Color? overlayColor;

  @override
  State createState() => GetSnackBarState();

  /// Show the snack. It's call [SnackbarStatus.opening] state
  /// followed by [SnackbarStatus.open]
  SnackbarController show() => Get.showSnackbar(this);
}

/// The state for managing a GetSnackBar widget.
class GetSnackBarState extends State<GetSnackBar>
    with TickerProviderStateMixin {
  // State variables and initialization code here

  /// Animation controller for the fading animation of the snack bar.
  AnimationController? _fadeController;

  /// Widget used to represent an empty space.
  final Widget _emptyWidget = const SizedBox.shrink();

  /// Focus scope node for managing focus within the snack bar.
  FocusScopeNode? _focusNode;

  /// Attachment for managing focus within the snack bar.
  late FocusAttachment _focusAttachment;

  /// Completer used to get the height of the snack bar.
  final Completer<Size> _boxHeightCompleter = Completer<Size>();

  /// GlobalKey used to access the background box widget.
  final GlobalKey<State<StatefulWidget>> _backgroundBoxKey = GlobalKey();

  /// Calculates the padding for the action button within the snack bar.
  double get buttonPadding {
    final double result = widget.padding.right - 12;
    return result < 0 ? 4 : result;
  }

  /// Determines the style of the row based on the presence of main button and icon.
  RowStyle get _rowStyle {
    return RowStyle.none;
  }

  @override
  Widget build(BuildContext context) {
    if (widget.disableSelfAlignment) {
      return _snackBar(context);
    } else {
      return Align(
        heightFactor: 1,
        child: _snackBar(context),
      );
    }
  }

  Material _snackBar(BuildContext context) => Material(
        elevation: 0,
        borderRadius: BorderRadius.circular(widget.borderRadius),
        color: Colors.transparent,
        shadowColor: Colors.transparent,
        child: SafeArea(
          minimum: widget.snackPosition == SnackPosition.bottom
              ? EdgeInsets.only(
                  bottom: MediaQuery.of(context).viewInsets.bottom,
                )
              : EdgeInsets.only(top: MediaQuery.of(context).padding.top),
          bottom: widget.snackPosition == SnackPosition.bottom,
          top: widget.snackPosition == SnackPosition.top,
          left: false,
          right: false,
          child: Stack(
            children: <Widget>[
              FutureBuilder<Size>(
                future: _boxHeightCompleter.future,
                builder: (BuildContext context, AsyncSnapshot<Size> snapshot) {
                  if (snapshot.hasData) {
                    if (widget.barBlur == 0) {
                      return _emptyWidget;
                    }
                    return ClipRRect(
                      borderRadius: BorderRadius.circular(widget.borderRadius),
                      child: BackdropFilter(
                        filter: ImageFilter.blur(
                          sigmaX: widget.barBlur,
                          sigmaY: widget.barBlur,
                        ),
                        child: Container(
                          height: snapshot.data!.height,
                          width: snapshot.data!.width,
                          color: Colors.transparent,
                        ),
                      ),
                    );
                  } else {
                    return _emptyWidget;
                  }
                },
              ),
              _containerWithoutForm(),
            ],
          ),
        ),
      );

  @override
  void dispose() {
    _fadeController?.dispose();

    _focusAttachment.detach();
    _focusNode!.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _configureLeftBarFuture();

    _focusNode = FocusScopeNode();
    _focusAttachment = _focusNode!.attach(context);
  }

  void _configureLeftBarFuture() {
    Engine.instance.addPostFrameCallback(
      (_) {
        final BuildContext? keyContext = _backgroundBoxKey.currentContext;
        if (keyContext != null) {
          final RenderBox box = keyContext.findRenderObject()! as RenderBox;
          _boxHeightCompleter.complete(box.size);
        }
      },
    );
  }

  Widget _containerWithoutForm() {
    final double left = _rowStyle == RowStyle.icon || _rowStyle == RowStyle.all
        ? 4.0
        : widget.padding.left;
    final double right =
        _rowStyle == RowStyle.action || _rowStyle == RowStyle.all
            ? 8.0
            : widget.padding.right;
    return Container(
      key: _backgroundBoxKey,
      constraints: widget.maxWidth != null
          ? BoxConstraints(maxWidth: widget.maxWidth!)
          : null,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(widget.borderRadius),
        border: Border.all(
            color: const Color.fromRGBO(102, 204, 255, 0.1), width: 1),
        boxShadow: widget.boxShadows,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          _emptyWidget,
          Padding(
            padding: EdgeInsets.only(
              top: widget.padding.top,
              bottom: widget.padding.bottom,
              left: left,
              right: right,
            ),
            child: widget.titleText,
          ),
        ],
      ),
    );
  }
}
